# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animus_robot.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import animus_utils.animus_structs_pb2 as animus__structs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='animus_robot.proto',
  package='animus.robot',
  syntax='proto3',
  serialized_options=b'\n!com.cyberselves.animus.robotprotoB\020AnimusRobotProtoH\001Z\"github.com/dcam0050/AnimusMessages\242\002\020AnimusRobotProto\252\002\021Animus.RobotProto',
  serialized_pb=b'\n\x12\x61nimus_robot.proto\x12\x0c\x61nimus.robot\x1a\x14\x61nimus_structs.proto\"\xf8\x01\n\x05Robot\x12\x10\n\x08robot_id\x18\x01 \x01(\t\x12\x0c\n\x04make\x18\x02 \x01(\t\x12\r\n\x05model\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x15\n\rhardware_hash\x18\x05 \x01(\t\x12(\n\x07license\x18\x06 \x01(\x0b\x32\x17.animus.structs.License\x12\x11\n\tjoin_date\x18\x07 \x01(\x03\x12/\n\x0crobot_config\x18\t \x01(\x0b\x32\x19.animus.robot.RobotConfig\x12-\n\x0brobot_state\x18\n \x01(\x0b\x32\x18.animus.robot.RobotState\"\xc4\x01\n\x0bRobotConfig\x12\x14\n\x0c\x65nableRemote\x18\x01 \x01(\x08\x12\x18\n\x10\x61vailable_public\x18\x02 \x01(\x08\x12\x18\n\x10input_modalities\x18\x03 \x03(\t\x12\x19\n\x11output_modalities\x18\x04 \x03(\t\x12\x1b\n\x13internal_modalities\x18\x05 \x03(\t\x12\x33\n\x0eStrAudioParams\x18\x06 \x01(\x0b\x32\x1b.animus.structs.AudioParams\"l\n\nRobotState\x12\x11\n\tavailable\x18\x01 \x01(\x08\x12*\n\x08location\x18\x02 \x01(\x0b\x32\x18.animus.structs.Location\x12\n\n\x02IP\x18\x03 \x01(\t\x12\x13\n\x0bNetworkMode\x18\x04 \x01(\tB\x82\x01\n!com.cyberselves.animus.robotprotoB\x10\x41nimusRobotProtoH\x01Z\"github.com/dcam0050/AnimusMessages\xa2\x02\x10\x41nimusRobotProto\xaa\x02\x11\x41nimus.RobotProtob\x06proto3'
  ,
  dependencies=[animus__structs__pb2.DESCRIPTOR,])




_ROBOT = _descriptor.Descriptor(
  name='Robot',
  full_name='animus.robot.Robot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot_id', full_name='animus.robot.Robot.robot_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='make', full_name='animus.robot.Robot.make', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model', full_name='animus.robot.Robot.model', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='animus.robot.Robot.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='hardware_hash', full_name='animus.robot.Robot.hardware_hash', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='license', full_name='animus.robot.Robot.license', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='join_date', full_name='animus.robot.Robot.join_date', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='robot_config', full_name='animus.robot.Robot.robot_config', index=7,
      number=9, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='robot_state', full_name='animus.robot.Robot.robot_state', index=8,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=307,
)


_ROBOTCONFIG = _descriptor.Descriptor(
  name='RobotConfig',
  full_name='animus.robot.RobotConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='enableRemote', full_name='animus.robot.RobotConfig.enableRemote', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='available_public', full_name='animus.robot.RobotConfig.available_public', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='input_modalities', full_name='animus.robot.RobotConfig.input_modalities', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='output_modalities', full_name='animus.robot.RobotConfig.output_modalities', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='internal_modalities', full_name='animus.robot.RobotConfig.internal_modalities', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='StrAudioParams', full_name='animus.robot.RobotConfig.StrAudioParams', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=310,
  serialized_end=506,
)


_ROBOTSTATE = _descriptor.Descriptor(
  name='RobotState',
  full_name='animus.robot.RobotState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='available', full_name='animus.robot.RobotState.available', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='location', full_name='animus.robot.RobotState.location', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='IP', full_name='animus.robot.RobotState.IP', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='NetworkMode', full_name='animus.robot.RobotState.NetworkMode', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=508,
  serialized_end=616,
)

_ROBOT.fields_by_name['license'].message_type = animus__structs__pb2._LICENSE
_ROBOT.fields_by_name['robot_config'].message_type = _ROBOTCONFIG
_ROBOT.fields_by_name['robot_state'].message_type = _ROBOTSTATE
_ROBOTCONFIG.fields_by_name['StrAudioParams'].message_type = animus__structs__pb2._AUDIOPARAMS
_ROBOTSTATE.fields_by_name['location'].message_type = animus__structs__pb2._LOCATION
DESCRIPTOR.message_types_by_name['Robot'] = _ROBOT
DESCRIPTOR.message_types_by_name['RobotConfig'] = _ROBOTCONFIG
DESCRIPTOR.message_types_by_name['RobotState'] = _ROBOTSTATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Robot = _reflection.GeneratedProtocolMessageType('Robot', (_message.Message,), {
  'DESCRIPTOR' : _ROBOT,
  '__module__' : 'animus_robot_pb2'
  # @@protoc_insertion_point(class_scope:animus.robot.Robot)
  })
_sym_db.RegisterMessage(Robot)

RobotConfig = _reflection.GeneratedProtocolMessageType('RobotConfig', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTCONFIG,
  '__module__' : 'animus_robot_pb2'
  # @@protoc_insertion_point(class_scope:animus.robot.RobotConfig)
  })
_sym_db.RegisterMessage(RobotConfig)

RobotState = _reflection.GeneratedProtocolMessageType('RobotState', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTSTATE,
  '__module__' : 'animus_robot_pb2'
  # @@protoc_insertion_point(class_scope:animus.robot.RobotState)
  })
_sym_db.RegisterMessage(RobotState)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
