# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animus_client.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import animus_utils.animus_structs_pb2 as animus__structs__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='animus_client.proto',
  package='animus.client',
  syntax='proto3',
  serialized_options=b'\n\"com.cyberselves.animus.clientprotoB\021AnimusClientProtoH\001Z\"github.com/dcam0050/AnimusMessages\242\002\021AnimusClientProto\252\002\022Animus.ClientProto',
  serialized_pb=b'\n\x13\x61nimus_client.proto\x12\ranimus.client\x1a\x14\x61nimus_structs.proto\"\xe3\x01\n\x04User\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x11\n\tyear_born\x18\x05 \x01(\x05\x12\x0f\n\x07\x63ountry\x18\x06 \x01(\t\x12\x11\n\tmarketing\x18\x07 \x01(\x08\x12\x13\n\x0btermsagreed\x18\x08 \x01(\x08\x12\x0f\n\x07\x63ompany\x18\t \x01(\t\x12\x12\n\nprofession\x18\n \x01(\t\x12\x11\n\tjoin_date\x18\x0b \x01(\x03\x12\x17\n\x0f\x65mail_validated\x18\x0c \x01(\x08\"\xc6\x01\n\x0cUserLicenses\x12\r\n\x05\x45mail\x18\x01 \x01(\t\x12\x34\n\x0e\x61sset_licenses\x18\x03 \x03(\x0b\x32\x1c.animus.structs.AssetLicense\x12\x34\n\x0erobot_licenses\x18\x04 \x03(\x0b\x32\x1c.animus.structs.RobotLicense\x12;\n\x15shared_robot_licenses\x18\x05 \x03(\x0b\x32\x1c.animus.structs.RobotLicenseB\x86\x01\n\"com.cyberselves.animus.clientprotoB\x11\x41nimusClientProtoH\x01Z\"github.com/dcam0050/AnimusMessages\xa2\x02\x11\x41nimusClientProto\xaa\x02\x12\x41nimus.ClientProtob\x06proto3'
  ,
  dependencies=[animus__structs__pb2.DESCRIPTOR,])




_USER = _descriptor.Descriptor(
  name='User',
  full_name='animus.client.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user_id', full_name='animus.client.User.user_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email', full_name='animus.client.User.email', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='password', full_name='animus.client.User.password', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='animus.client.User.name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='year_born', full_name='animus.client.User.year_born', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='country', full_name='animus.client.User.country', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='marketing', full_name='animus.client.User.marketing', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='termsagreed', full_name='animus.client.User.termsagreed', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='company', full_name='animus.client.User.company', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='profession', full_name='animus.client.User.profession', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='join_date', full_name='animus.client.User.join_date', index=10,
      number=11, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='email_validated', full_name='animus.client.User.email_validated', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=288,
)


_USERLICENSES = _descriptor.Descriptor(
  name='UserLicenses',
  full_name='animus.client.UserLicenses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Email', full_name='animus.client.UserLicenses.Email', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='asset_licenses', full_name='animus.client.UserLicenses.asset_licenses', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='robot_licenses', full_name='animus.client.UserLicenses.robot_licenses', index=2,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='shared_robot_licenses', full_name='animus.client.UserLicenses.shared_robot_licenses', index=3,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=291,
  serialized_end=489,
)

_USERLICENSES.fields_by_name['asset_licenses'].message_type = animus__structs__pb2._ASSETLICENSE
_USERLICENSES.fields_by_name['robot_licenses'].message_type = animus__structs__pb2._ROBOTLICENSE
_USERLICENSES.fields_by_name['shared_robot_licenses'].message_type = animus__structs__pb2._ROBOTLICENSE
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['UserLicenses'] = _USERLICENSES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'animus_client_pb2'
  # @@protoc_insertion_point(class_scope:animus.client.User)
  })
_sym_db.RegisterMessage(User)

UserLicenses = _reflection.GeneratedProtocolMessageType('UserLicenses', (_message.Message,), {
  'DESCRIPTOR' : _USERLICENSES,
  '__module__' : 'animus_client_pb2'
  # @@protoc_insertion_point(class_scope:animus.client.UserLicenses)
  })
_sym_db.RegisterMessage(UserLicenses)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
