# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: animus_robot_sdk.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import animus_utils.animus_robot_pb2 as animus__robot__pb2
import animus_utils.animus_common_pb2 as animus__common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='animus_robot_sdk.proto',
  package='animus.robot_sdk',
  syntax='proto3',
  serialized_options=b'\n\031com.cyberselves.robot_sdkB\023AnimusRobotSDKProtoH\001Z\"github.com/dcam0050/AnimusMessages\242\002\016AnimusRobotSDK\252\002\017Animus.RobotSDK',
  serialized_pb=b'\n\x16\x61nimus_robot_sdk.proto\x12\x10\x61nimus.robot_sdk\x1a\x12\x61nimus_robot.proto\x1a\x13\x61nimus_common.proto\"0\n\x0fSetupRobotProto\x12\x0e\n\x06logDir\x18\x01 \x01(\t\x12\r\n\x05\x44\x65\x62ug\x18\x02 \x01(\x08\"c\n\x14StartRobotCommsProto\x12\x12\n\nstartLocal\x18\x01 \x01(\x08\x12\x13\n\x0bstartRemote\x18\x02 \x01(\x08\x12\"\n\x05robot\x18\x03 \x01(\x0b\x32\x13.animus.robot.Robot\"[\n\x10RobotConfigProto\x12\"\n\x05robot\x18\x01 \x01(\x0b\x32\x13.animus.robot.Robot\x12#\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x14.animus.common.ErrorBy\n\x19\x63om.cyberselves.robot_sdkB\x13\x41nimusRobotSDKProtoH\x01Z\"github.com/dcam0050/AnimusMessages\xa2\x02\x0e\x41nimusRobotSDK\xaa\x02\x0f\x41nimus.RobotSDKb\x06proto3'
  ,
  dependencies=[animus__robot__pb2.DESCRIPTOR,animus__common__pb2.DESCRIPTOR,])




_SETUPROBOTPROTO = _descriptor.Descriptor(
  name='SetupRobotProto',
  full_name='animus.robot_sdk.SetupRobotProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='logDir', full_name='animus.robot_sdk.SetupRobotProto.logDir', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Debug', full_name='animus.robot_sdk.SetupRobotProto.Debug', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=133,
)


_STARTROBOTCOMMSPROTO = _descriptor.Descriptor(
  name='StartRobotCommsProto',
  full_name='animus.robot_sdk.StartRobotCommsProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='startLocal', full_name='animus.robot_sdk.StartRobotCommsProto.startLocal', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='startRemote', full_name='animus.robot_sdk.StartRobotCommsProto.startRemote', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='robot', full_name='animus.robot_sdk.StartRobotCommsProto.robot', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=234,
)


_ROBOTCONFIGPROTO = _descriptor.Descriptor(
  name='RobotConfigProto',
  full_name='animus.robot_sdk.RobotConfigProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='robot', full_name='animus.robot_sdk.RobotConfigProto.robot', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='animus.robot_sdk.RobotConfigProto.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=327,
)

_STARTROBOTCOMMSPROTO.fields_by_name['robot'].message_type = animus__robot__pb2._ROBOT
_ROBOTCONFIGPROTO.fields_by_name['robot'].message_type = animus__robot__pb2._ROBOT
_ROBOTCONFIGPROTO.fields_by_name['error'].message_type = animus__common__pb2._ERROR
DESCRIPTOR.message_types_by_name['SetupRobotProto'] = _SETUPROBOTPROTO
DESCRIPTOR.message_types_by_name['StartRobotCommsProto'] = _STARTROBOTCOMMSPROTO
DESCRIPTOR.message_types_by_name['RobotConfigProto'] = _ROBOTCONFIGPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SetupRobotProto = _reflection.GeneratedProtocolMessageType('SetupRobotProto', (_message.Message,), {
  'DESCRIPTOR' : _SETUPROBOTPROTO,
  '__module__' : 'animus_robot_sdk_pb2'
  # @@protoc_insertion_point(class_scope:animus.robot_sdk.SetupRobotProto)
  })
_sym_db.RegisterMessage(SetupRobotProto)

StartRobotCommsProto = _reflection.GeneratedProtocolMessageType('StartRobotCommsProto', (_message.Message,), {
  'DESCRIPTOR' : _STARTROBOTCOMMSPROTO,
  '__module__' : 'animus_robot_sdk_pb2'
  # @@protoc_insertion_point(class_scope:animus.robot_sdk.StartRobotCommsProto)
  })
_sym_db.RegisterMessage(StartRobotCommsProto)

RobotConfigProto = _reflection.GeneratedProtocolMessageType('RobotConfigProto', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTCONFIGPROTO,
  '__module__' : 'animus_robot_sdk_pb2'
  # @@protoc_insertion_point(class_scope:animus.robot_sdk.RobotConfigProto)
  })
_sym_db.RegisterMessage(RobotConfigProto)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
